### ISSUE TITLE
引包问题

### ISSUE THREAD

**Issue by hanjieliao** [DimBottom/seata1.4.1-sample#1]
为啥storage引入的是seata-spring-boot-starter的包  其他两个项目是spring-cloud-starter-alibaba-seata， 而且把storage的换成spring-cloud-starter-alibaba-seata会报错

**Comment by DimBottom** [comment]
本来我也是推荐使用 spring-cloud-starter-alibaba-seata 的，但是实际项目测试下来 seata-spring-boot-starter 兼容性更好些，具体原因是依赖中 ribbon 版本的问题，所以推荐用后者啦
